/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '9/02/16 9:28' with Gradle 2.6
 *
 * @author mati, @date 9/02/16 9:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
